### PR TITLE
Chore: Paper migration

### PR DESCRIPTION
**Pull request by Quentixx**
## Context
The Minestom library ultimately does not meet our needs from a maintainability point of view.
After some consideration, @Distractic, @Bananasmoothii and I agreed to migrate the library to PaperMC which is a fork of the Spigot project.

## Benefits
- Maintainability of the project over time
- Development team already at ease with the library
- Basic server behaviors required
- Stability

## Disadvantages compared to Minestom
- Loss of performance
- Unit Tests
- Packet handling
- Not fully open-source

## Objective of the PR
- Adapt the code initially designed under Minestom to PaperMC
- Review the tests

### CODE REVIEW

**Comment by bananasmoothii** [comment]
Maybe we can make some parts with minestom and some other parts with paper and like both with a proxy (velocity for instance) because minestom is much cheaper when it comes to hosting as it requires less performance

**Comment by Quentixx** [comment]
It's an interesting idea but it requires redesigning the API to handle PaperMC and Minestom.

It should be clarified in which use cases Minestom is preferable:
---
* **Hub** - Minestom
   - 👍 _Because the hub server by design does not affect pvp_
   - 👍 _The scoreboard is very cool to handle_
   - 👍 _The food supporting is not necessary_
    ---
   - 👎 _Currently, the mount system is bugged (move + jump)_ https://github.com/Rushyverse/hub/blob/feat/mount/src/main/kotlin/fr/rushy/hub/command/PigCommand.kt
   - 👎 _For the Guild system, I want to do a banner customizable system (pattern + colors), I did not find how to do this under Minestom_
---
* **Pvpbox** - Paper 
   - 👍 _The current dev of this project (@Cizetux) is more comfortable with Bukkit based environnement_
   - 👍 _Not necessary to add any PvpExtension_
    ---
   - 👎 _Need to cancel some events (FoodLevelChange, WeatherChangeEvent, ...) while Minestom saves us from doing this_
---
* **GameIdea1** - Paper/Minestom ❓ 
   - 📦 I think It depends if the game concept is built around interactions between players
---
What is your opinion about these use cases @bananasmoothii ?

**Comment by bananasmoothii** [comment]
Yes, that is probably a good way. The connection between servers could be made via redis

**Comment by Distractic** [comment]
Having two types of server (Minestom and Spigot) is a real challenge and requires a lot of work. Because when you have to implement a feature on one, you will probably have to implement it on the other. This will require having two APIs to maintain.

Concerning the communication between the servers, whatever the type, the servers will be able to communicate between them using the proxy and to send messages to each other using redis

**Pull request merged**
